/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "Common.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(BoardStatus, BoardStatus, AUTO)


PB_BIND(WatchdogConfig, WatchdogConfig, AUTO)


PB_BIND(WatchdogStatus, WatchdogStatus, AUTO)


PB_BIND(EmergencyStop, EmergencyStop, AUTO)





