/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PROTOS_GPIO_PB_H_INCLUDED
#define PB_PROTOS_GPIO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _DigitalOutputStates {
    bool states[4];
} DigitalOutputStates;

typedef struct _DigitalInputStates {
    bool states[4];
} DigitalInputStates;

typedef struct _AnalogInputStates {
    float states[4];
    bool hysteresis_state;
} AnalogInputStates;

typedef struct _DigitalInputConfig {
    bool send_periodically_states;
    uint32_t send_period;
    bool send_on_change[4];
} DigitalInputConfig;

typedef struct _AnalogInputConfig {
    bool send_periodically_states;
    uint32_t send_period;
    float offset[4];
    float scale[4];
    bool send_hysteresis_state[4];
    float hysteresis_high[4];
    float hysteresis_low[4];
} AnalogInputConfig;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define DigitalOutputStates_init_default         {{0, 0, 0, 0}}
#define DigitalInputStates_init_default          {{0, 0, 0, 0}}
#define AnalogInputStates_init_default           {{0, 0, 0, 0}, 0}
#define DigitalInputConfig_init_default          {0, 0, {0, 0, 0, 0}}
#define AnalogInputConfig_init_default           {0, 0, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}}
#define DigitalOutputStates_init_zero            {{0, 0, 0, 0}}
#define DigitalInputStates_init_zero             {{0, 0, 0, 0}}
#define AnalogInputStates_init_zero              {{0, 0, 0, 0}, 0}
#define DigitalInputConfig_init_zero             {0, 0, {0, 0, 0, 0}}
#define AnalogInputConfig_init_zero              {0, 0, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}}

/* Field tags (for use in manual encoding/decoding) */
#define DigitalOutputStates_states_tag           1
#define DigitalInputStates_states_tag            1
#define AnalogInputStates_states_tag             1
#define AnalogInputStates_hysteresis_state_tag   2
#define DigitalInputConfig_send_periodically_states_tag 1
#define DigitalInputConfig_send_period_tag       2
#define DigitalInputConfig_send_on_change_tag    3
#define AnalogInputConfig_send_periodically_states_tag 1
#define AnalogInputConfig_send_period_tag        2
#define AnalogInputConfig_offset_tag             3
#define AnalogInputConfig_scale_tag              4
#define AnalogInputConfig_send_hysteresis_state_tag 5
#define AnalogInputConfig_hysteresis_high_tag    6
#define AnalogInputConfig_hysteresis_low_tag     7

/* Struct field encoding specification for nanopb */
#define DigitalOutputStates_FIELDLIST(X, a) \
X(a, STATIC,   FIXARRAY, BOOL,     states,            1)
#define DigitalOutputStates_CALLBACK NULL
#define DigitalOutputStates_DEFAULT NULL

#define DigitalInputStates_FIELDLIST(X, a) \
X(a, STATIC,   FIXARRAY, BOOL,     states,            1)
#define DigitalInputStates_CALLBACK NULL
#define DigitalInputStates_DEFAULT NULL

#define AnalogInputStates_FIELDLIST(X, a) \
X(a, STATIC,   FIXARRAY, FLOAT,    states,            1) \
X(a, STATIC,   REQUIRED, BOOL,     hysteresis_state,   2)
#define AnalogInputStates_CALLBACK NULL
#define AnalogInputStates_DEFAULT NULL

#define DigitalInputConfig_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     send_periodically_states,   1) \
X(a, STATIC,   REQUIRED, UINT32,   send_period,       2) \
X(a, STATIC,   FIXARRAY, BOOL,     send_on_change,    3)
#define DigitalInputConfig_CALLBACK NULL
#define DigitalInputConfig_DEFAULT NULL

#define AnalogInputConfig_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     send_periodically_states,   1) \
X(a, STATIC,   REQUIRED, UINT32,   send_period,       2) \
X(a, STATIC,   FIXARRAY, FLOAT,    offset,            3) \
X(a, STATIC,   FIXARRAY, FLOAT,    scale,             4) \
X(a, STATIC,   FIXARRAY, BOOL,     send_hysteresis_state,   5) \
X(a, STATIC,   FIXARRAY, FLOAT,    hysteresis_high,   6) \
X(a, STATIC,   FIXARRAY, FLOAT,    hysteresis_low,    7)
#define AnalogInputConfig_CALLBACK NULL
#define AnalogInputConfig_DEFAULT NULL

extern const pb_msgdesc_t DigitalOutputStates_msg;
extern const pb_msgdesc_t DigitalInputStates_msg;
extern const pb_msgdesc_t AnalogInputStates_msg;
extern const pb_msgdesc_t DigitalInputConfig_msg;
extern const pb_msgdesc_t AnalogInputConfig_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define DigitalOutputStates_fields &DigitalOutputStates_msg
#define DigitalInputStates_fields &DigitalInputStates_msg
#define AnalogInputStates_fields &AnalogInputStates_msg
#define DigitalInputConfig_fields &DigitalInputConfig_msg
#define AnalogInputConfig_fields &AnalogInputConfig_msg

/* Maximum encoded size of messages (where known) */
#define AnalogInputConfig_size                   96
#define AnalogInputStates_size                   22
#define DigitalInputConfig_size                  16
#define DigitalInputStates_size                  8
#define DigitalOutputStates_size                 8
#define PROTOS_GPIO_PB_H_MAX_SIZE                AnalogInputConfig_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
