/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "GPIO.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(DigitalOutputStates, DigitalOutputStates, AUTO)


PB_BIND(DigitalInputStates, DigitalInputStates, AUTO)


PB_BIND(AnalogInputStates, AnalogInputStates, AUTO)


PB_BIND(DigitalInputConfig, DigitalInputConfig, AUTO)


PB_BIND(AnalogInputConfig, AnalogInputConfig, AUTO)



