/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PROTOS_SERVO_PB_H_INCLUDED
#define PB_PROTOS_SERVO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ServoById {
    uint32_t servoID;
    float position;
} ServoById;

typedef struct _ServoEnable {
    bool enable;
} ServoEnable;

typedef struct _ServoVoltage {
    float voltage;
} ServoVoltage;

typedef struct _ServoStatus {
    float positions[4];
} ServoStatus;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ServoById_init_default                   {0, 0}
#define ServoEnable_init_default                 {0}
#define ServoVoltage_init_default                {0}
#define ServoStatus_init_default                 {{0, 0, 0, 0}}
#define ServoById_init_zero                      {0, 0}
#define ServoEnable_init_zero                    {0}
#define ServoVoltage_init_zero                   {0}
#define ServoStatus_init_zero                    {{0, 0, 0, 0}}

/* Field tags (for use in manual encoding/decoding) */
#define ServoById_servoID_tag                    1
#define ServoById_position_tag                   2
#define ServoEnable_enable_tag                   1
#define ServoVoltage_voltage_tag                 1
#define ServoStatus_positions_tag                1

/* Struct field encoding specification for nanopb */
#define ServoById_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   servoID,           1) \
X(a, STATIC,   REQUIRED, FLOAT,    position,          2)
#define ServoById_CALLBACK NULL
#define ServoById_DEFAULT NULL

#define ServoEnable_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     enable,            1)
#define ServoEnable_CALLBACK NULL
#define ServoEnable_DEFAULT NULL

#define ServoVoltage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    voltage,           1)
#define ServoVoltage_CALLBACK NULL
#define ServoVoltage_DEFAULT NULL

#define ServoStatus_FIELDLIST(X, a) \
X(a, STATIC,   FIXARRAY, FLOAT,    positions,         1)
#define ServoStatus_CALLBACK NULL
#define ServoStatus_DEFAULT NULL

extern const pb_msgdesc_t ServoById_msg;
extern const pb_msgdesc_t ServoEnable_msg;
extern const pb_msgdesc_t ServoVoltage_msg;
extern const pb_msgdesc_t ServoStatus_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ServoById_fields &ServoById_msg
#define ServoEnable_fields &ServoEnable_msg
#define ServoVoltage_fields &ServoVoltage_msg
#define ServoStatus_fields &ServoStatus_msg

/* Maximum encoded size of messages (where known) */
#define PROTOS_SERVO_PB_H_MAX_SIZE               ServoStatus_size
#define ServoById_size                           11
#define ServoEnable_size                         2
#define ServoStatus_size                         20
#define ServoVoltage_size                        5

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
