/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "Servo.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ServoById, ServoById, AUTO)


PB_BIND(ServoEnable, ServoEnable, AUTO)


PB_BIND(ServoVoltage, ServoVoltage, AUTO)


PB_BIND(ServoStatus, ServoStatus, AUTO)



